[package]
name = "panopticon-ics"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version="3.2.18", features=["derive"]}
eframe = "0.19.0"
ics = "0.5.7"
image = "0.24.3"
sscanf = "0.3.1"
