[package]
name = "panopticon-ics"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
eframe = "0.24.1"
egui_extras = { version = "0.24.2", features = ["image"] }
image = { version = "0.24.8", features = ["png", "farbfeld"] }
ics = "0.5.8"
sscanf = "0.4.1"
