[package]
name = "panopticon-ics"
version = "0.1.0"
edition="2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.45"
clap = { version = "4.6.1", features = ["derive"] }
eframe = "0.34.3"
egui_extras = { version = "0.34.3", features = ["image", "file"] }
image = { version = "0.25.10", features = ["png"] }
ics = "0.5.8"
sscanf = "0.5.0"
