[package]
name = "panopticon"
version = "0.1.0"
edition="2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
rand = "0.9.0"
xcap = "0.4.0"
user-idle = "0.6.0"

