[package]
name = "panopticon"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
rand = "0.8.5"
xcap = "0.2.0"
user-idle = "0.6.0"

