[package]
name = "icsbuilder"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="3.2.18", features=["derive"]}
eframe = "0.19.0"
ics = "0.5.7"
